# Generated by Django 6.0.5 on 2026-07-26 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_client_photo'),
        ('catalog', '0032_promotion_description_promotion_heure_debut_and_more'),
        ('support', '0005_alter_agentsupportclient_id_alter_avis_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='achat_verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avis',
            name='date_reponse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avis',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='avis',
            name='reponse_fournisseur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avis',
            name='reponse_fournisseur_nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='avis',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='account.client'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='catalog.produit'),
        ),
        migrations.CreateModel(
            name='SignalementAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('offensant', 'Langage offensant'), ('spam', 'Spam'), ('faux', 'Faux avis'), ('inapproprie', 'Contenu inapproprié')], max_length=50)),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('avis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='support.avis')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_signalements', to='account.fournisseur')),
            ],
        ),
    ]
