# Generated by Django 6.0.5 on 2026-07-29 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_fournisseur_statut'),
        ('catalog', '0033_marque_alter_categorie_options_categorie_ordre'),
        ('orders', '0008_commande_commentaire_fournisseur_and_more'),
        ('support', '0006_avis_achat_verifie_avis_date_reponse_avis_photos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclamation',
            options={'ordering': ['-date_soumission']},
        ),
        migrations.AddField(
            model_name='reclamation',
            name='assigne_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_assignees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='date_derniere_maj',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='date_ouverture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='date_resolution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='est_litige',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='account.fournisseur'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='motif',
            field=models.CharField(blank=True, choices=[('produit_non_conforme', 'Produit non conforme'), ('produit_defectueux', 'Produit défectueux'), ('produit_manquant', 'Produit manquant'), ('livraison_retardee', 'Livraison retardée'), ('livraison_non_recue', 'Livraison non reçue'), ('facturation_incorrecte', 'Facturation incorrecte'), ('remboursement', 'Demande de remboursement'), ('echange', "Demande d'échange"), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='note_interne',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='numero_dossier',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='priorite',
            field=models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('elevee', 'Élevée'), ('urgente', 'Urgente')], default='normale', max_length=20),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='catalog.produit'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='raison_rejet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='reponse_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='account.client'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='orders.commande'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours_analyse', "En cours d'analyse"), ('en_attente_infos', "En attente d'informations"), ('resolu', 'Résolu'), ('rejete', 'Rejeté'), ('ferme', 'Fermé')], default='nouveau', max_length=30),
        ),
        migrations.AlterModelTable(
            name='reclamation',
            table='support_reclamation',
        ),
        migrations.CreateModel(
            name='HistoriqueReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création du dossier'), ('ouverture', 'Ouverture du dossier'), ('reponse', 'Réponse ajoutée'), ('demande_infos', "Demande d'informations"), ('changement_priorite', 'Changement de priorité'), ('changement_statut', 'Changement de statut'), ('assignation', 'Assignation'), ('note_interne', 'Note interne'), ('resolution', 'Résolution'), ('rejet', 'Rejet'), ('fermeture', 'Fermeture'), ('modification', 'Modification')], max_length=30)),
                ('statut', models.CharField(blank=True, max_length=30)),
                ('priorite', models.CharField(blank=True, max_length=20)),
                ('auteur_nom', models.CharField(blank=True, max_length=100)),
                ('auteur_type', models.CharField(blank=True, max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='support.reclamation')),
            ],
            options={
                'db_table': 'support_historique_reclamation',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MessageReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur_type', models.CharField(choices=[('client', 'Client'), ('fournisseur', 'Fournisseur'), ('admin', 'Administrateur'), ('systeme', 'Système')], max_length=20)),
                ('auteur_nom', models.CharField(blank=True, max_length=100)),
                ('contenu', models.TextField()),
                ('est_note_interne', models.BooleanField(default=False)),
                ('est_visible_client', models.BooleanField(default=True)),
                ('est_visible_fournisseur', models.BooleanField(default=True)),
                ('lu_par_client', models.BooleanField(default=False)),
                ('lu_par_fournisseur', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.reclamation')),
            ],
            options={
                'db_table': 'support_message_reclamation',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointeReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='reclamations/%Y/%m/')),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('pdf', 'PDF'), ('facture', 'Facture'), ('capture', "Capture d'écran"), ('autre', 'Autre')], default='autre', max_length=20)),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='support.messagereclamation')),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='support.reclamation')),
            ],
            options={
                'db_table': 'support_piecejointe_reclamation',
            },
        ),
    ]
