# Generated by Django 6.0.5 on 2026-08-09 02:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_fournisseur_statut'),
        ('catalog', '0036_produit_nombre_avis_produit_note_moyenne'),
        ('fournisseur', '0006_magasin_nombre_avis_magasin_note_moyenne'),
        ('orders', '0010_commande_adresse_livraison_commande_telephone_client_and_more'),
        ('support', '0007_alter_reclamation_options_reclamation_assigne_a_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='avis',
            name='approuve',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='avis',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis_commande', to='orders.commande'),
        ),
        migrations.AddField(
            model_name='avis',
            name='ligne_commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis_ligne', to='orders.lignecommande'),
        ),
        migrations.AddField(
            model_name='avis',
            name='magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='fournisseur.magasin'),
        ),
        migrations.AddField(
            model_name='avis',
            name='note_communication',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='avis',
            name='note_delai',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='avis',
            name='note_livraison',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='avis',
            name='note_qualite_produit',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='signalementavis',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signalements_avis', to='account.client'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='signalementavis',
            name='commentaire',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='signalementavis',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis_signalements', to='account.fournisseur'),
        ),
        migrations.AlterField(
            model_name='signalementavis',
            name='motif',
            field=models.CharField(choices=[('faux', 'Faux avis'), ('inapproprie', 'Contenu inapproprié'), ('offensant', 'Langage offensant / insulte'), ('insulte', 'Insulte'), ('spam', 'Spam'), ('informations_fausses', 'Informations fausses'), ('autre', 'Autre')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='avis',
            constraint=models.UniqueConstraint(condition=models.Q(('produit__isnull', False)), fields=('client', 'produit'), name='unique_avis_client_produit'),
        ),
        migrations.AddConstraint(
            model_name='avis',
            constraint=models.UniqueConstraint(condition=models.Q(('magasin__isnull', False)), fields=('client', 'magasin'), name='unique_avis_client_magasin'),
        ),
    ]
