# Generated by Django 6.0.5 on 2026-09-08 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_alter_avis_unique_together_avis_approuve_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePartenariat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('marque', models.CharField(blank=True, default='', max_length=200)),
                ('email_contact', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée')], default='nouvelle', max_length=20)),
                ('reponse_admin', models.TextField(blank=True, default='')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_partenariat_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_demande_partenariat',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
