# Generated by Django 6.0.5 on 2026-07-08 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_favori_id_alter_utilisateur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(
                choices=[('client', 'Client'), ('admin', 'Administrateur'), ('fournisseur', 'Fournisseur')],
                default='client',
                max_length=30
            ),
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.utilisateur')),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('ninea', models.CharField(blank=True, max_length=50, null=True)),
                ('agree_ninea', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('horaires', models.JSONField(blank=True, null=True)),
                ('banque_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('banque_iban', models.CharField(blank=True, max_length=50, null=True)),
                ('banque_mobile_money', models.CharField(blank=True, max_length=100, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('desactive', 'Désactivé')], default='actif', max_length=20)),
            ],
        ),
    ]
