# Generated by Django 6.0.5 on 2026-07-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20260708_1952'),
        ('catalog', '0020_remove_promotion_fournisseur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Administrateur')], default='client', max_length=30),
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
    ]
