# Generated by Django 6.0.5 on 2026-07-14 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_utilisateur_role_delete_fournisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('siret', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='fournisseurs/logos/')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('desactive', 'Désactivé'), ('attente', 'En attente')], default='attente', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('note_moyenne', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('nombre_avis', models.IntegerField(default=0)),
                ('nombre_produits', models.IntegerField(default=0)),
                ('nombre_ventes', models.IntegerField(default=0)),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'db_table': 'fournisseur',
            },
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Administrateur'), ('fournisseur', 'Fournisseur')], default='client', max_length=30),
        ),
    ]
