# Generated by Django 6.0.5 on 2026-07-16 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_fournisseur_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='email_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(blank=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('password_change', 'Changement de mot de passe'), ('password_change_failed', 'Échec changement mot de passe'), ('two_factor_enabled', '2FA activé'), ('two_factor_disabled', '2FA désactivé'), ('session_revoked', 'Session révoquée'), ('all_sessions_revoked', 'Toutes les sessions révoquées'), ('token_created', 'Clé API créée'), ('token_revoked', 'Clé API révoquée'), ('account_deactivated', 'Compte désactivé'), ('security_alert', 'Alerte sécurité')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Succès'), ('failure', 'Échec'), ('info', 'Info'), ('warning', 'Avertissement')], default='success', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_activity',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=128, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_session',
                'ordering': ['-last_active_at'],
            },
        ),
    ]
