# Generated by Django 6.0.5 on 2026-07-20 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_utilisateur_email_alerts_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='raison_refus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournisseurs_valides', to='account.administrateur'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente de validation'), ('actif', 'Validé'), ('desactive', 'Refusé / Suspendu')], default='attente', max_length=20),
        ),
        migrations.CreateModel(
            name='FournisseurStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournisseur_status_changes', to='account.administrateur')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='account.fournisseur')),
            ],
            options={
                'verbose_name': 'Historique statut fournisseur',
                'verbose_name_plural': 'Historiques statuts fournisseurs',
                'db_table': 'fournisseur_status_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
