# Generated by Django 6.0.5 on 2026-07-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_fournisseur_raison_refus_fournisseur_validated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/photos/'),
        ),
    ]
