# Generated by Django 6.0.5 on 2026-07-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_client_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente de validation'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('desactive', 'Désactivé')], default='attente', max_length=20),
        ),
    ]
