# Generated by Django 6.0.5 on 2026-08-09 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_fournisseur_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('annee', models.PositiveIntegerField()),
                ('motorisation', models.CharField(blank=True, default='', max_length=100)),
                ('carburant', models.CharField(blank=True, default='', max_length=50)),
                ('version', models.CharField(blank=True, default='', max_length=100)),
                ('immatriculation', models.CharField(blank=True, default='', max_length=20)),
                ('actif', models.BooleanField(default=False, help_text='Véhicule utilisé par défaut')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='account.client')),
            ],
            options={
                'verbose_name': 'Véhicule client',
                'verbose_name_plural': 'Véhicules clients',
                'db_table': 'client_vehicule',
                'ordering': ['-actif', '-date_ajout'],
            },
        ),
    ]
