# Generated by Django 6.0.5 on 2026-09-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_normalize_fournisseur_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='two_factor_backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
