# Generated by Django 6.0.5 on 2026-07-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_method', models.CharField(default='Token Authentication (HTTP Bearer)', max_length=100)),
                ('database_routing', models.CharField(default='PostgreSQL', max_length=100)),
            ],
            options={
                'verbose_name': 'Configuration API',
                'verbose_name_plural': 'Configurations API',
            },
        ),
        migrations.CreateModel(
            name='FinanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('base_shipping_fee', models.DecimalField(decimal_places=2, default=5.9, max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuration financière',
                'verbose_name_plural': 'Configurations financières',
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Passerelle de paiement',
                'verbose_name_plural': 'Passerelles de paiement',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('role_key', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Rôle et permission',
                'verbose_name_plural': 'Rôles et permissions',
            },
        ),
    ]
