# Generated by Django 5.2.6 on 2026-06-02 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_categorie_id_alter_entrepot_id_and_more'),
    ]

    operations = [
    ]
