# Generated by Django 6.0.5 on 2026-09-14 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_marque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_fournisseur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='administrateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_fournisseurs_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
