# Generated by Django 6.0.5 on 2026-07-08 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_favori_id_alter_utilisateur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favori',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Administrateur'), ('fournisseur', 'Fournisseur')], default='client', max_length=30),
        ),
        migrations.CreateModel(
            name='FournisseurProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fournisseur_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom_entreprise', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('siret', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='fournisseurs/logos/')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('actif', 'Actif'), ('suspendu', 'Suspendu')], default='en_attente', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('note_moyenne', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('nombre_avis', models.PositiveIntegerField(default=0)),
                ('nombre_produits', models.PositiveIntegerField(default=0)),
                ('nombre_ventes', models.PositiveIntegerField(default=0)),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournisseurs_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Fournisseur',
                'verbose_name_plural': 'Profils Fournisseurs',
                'db_table': 'fournisseur_profile',
            },
        ),
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('securite', 'Sécurité'), ('finances', 'Finances'), ('vendeurs', 'Vendeurs'), ('produits', 'Produits'), ('categories', 'Catégories'), ('systeme', 'Système')], max_length=20)),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('validation', 'Validation'), ('suspension', 'Suspension'), ('connexion', 'Connexion'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrée du journal',
                'verbose_name_plural': "Journal d'activité",
                'db_table': 'journal_activite',
                'ordering': ['-date_creation'],
            },
        ),
    ]
