# Generated by Django 6.0.1 on 2026-02-25 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_utilisateur_options_utilisateur_date_joined_and_more'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='invite',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.RemoveField(
            model_name='rapportinventaire',
            name='gestionnaire_stock',
        ),
        migrations.RemoveField(
            model_name='rapportinventairestock',
            name='rapport_inventaire',
        ),
        migrations.RemoveField(
            model_name='rapportinventairestock',
            name='stock',
        ),
        migrations.AlterField(
            model_name='categorie',
            name='categorieid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='datecreation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='datemodification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='etat',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='entrepot',
            name='capacite_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrepot',
            name='gestionnaire_stock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.gestionnairestock'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='administrateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='contrat_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fournisseurproduit',
            name='stock_initial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='date_mouvement',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='gestionnaire_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.gestionnairestock'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.produit'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.stock'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='catalog.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='gestionnaire_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.gestionnairestock'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produitfavoris',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_derniere_maj',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='gestionnaire_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.gestionnairestock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantite_actuelle',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='seuil_critique',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='produitfavoris',
            unique_together={('client', 'produit')},
        ),
        migrations.DeleteModel(
            name='Navigation',
        ),
        migrations.DeleteModel(
            name='RapportInventaire',
        ),
        migrations.DeleteModel(
            name='RapportInventaireStock',
        ),
    ]
