# Generated by Django 6.0.1 on 2026-05-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_produit_date_fin_promo_produit_est_en_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
