# Generated by Django 6.0.6 on 2026-06-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_add_product_additional_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande_id', models.CharField(max_length=100, verbose_name='N° Commande')),
                ('client', models.CharField(max_length=255, verbose_name='Client')),
                ('adresse', models.TextField(verbose_name='Adresse de livraison')),
                ('statut', models.CharField(choices=[('en_preparation', 'En préparation'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_preparation', max_length=20, verbose_name='Statut')),
                ('transporteur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transporteur')),
                ('tracking', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de tracking')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_livraison', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison effective')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_creation'],
            },
        ),
    ]
