# Generated by Django 6.0.5 on 2026-07-11 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20260708_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='produit',
        ),
        migrations.DeleteModel(
            name='Avis',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
