# Generated by Django 6.0.5 on 2026-07-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_remove_promotion_fournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='statut_approbation',
            field=models.CharField(
                choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')],
                default='en_attente',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='produit',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
