# Generated by Django 6.0.5 on 2026-07-13 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20260713_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='motif_rejet',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='statut_approbation',
        ),
    ]
