# Generated by Django 6.0.5 on 2026-07-14 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_fournisseur_alter_utilisateur_role'),
        ('catalog', '0023_alter_fournisseur_administrateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='account.fournisseur'),
        ),
    ]
