# Generated by Django 6.0.5 on 2026-07-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='signale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produit',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=20),
        ),
        migrations.AddField(
            model_name='produit',
            name='statut_approbation',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20),
        ),
    ]
