# Generated by Django 6.0.5 on 2026-07-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_produit_motif_rejet_produit_signale_produit_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='est_meilleure_offre',
            field=models.BooleanField(default=False, help_text='Meilleure offre / bon plan'),
        ),
    ]
