# Generated by Django 6.0.5 on 2026-07-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_produit_est_meilleure_offre'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='annee_debut',
            field=models.PositiveIntegerField(blank=True, help_text='Année de début de compatibilité', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='annee_fin',
            field=models.PositiveIntegerField(blank=True, help_text='Année de fin de compatibilité', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='conditions_retour',
            field=models.TextField(blank=True, default='', help_text='Conditions de retour'),
        ),
        migrations.AddField(
            model_name='produit',
            name='conseils_installation',
            field=models.TextField(blank=True, default='', help_text="Conseils d'installation"),
        ),
        migrations.AddField(
            model_name='produit',
            name='delai_livraison',
            field=models.CharField(blank=True, choices=[('same_day', 'Livraison le jour même'), ('24h', '24 heures'), ('48h', '48 heures'), ('2_5j', '2 à 5 jours'), ('5_7j', '5 à 7 jours'), ('7j_plus', 'Plus de 7 jours')], default='2_5j', max_length=20),
        ),
        migrations.AddField(
            model_name='produit',
            name='disponibilite',
            field=models.CharField(blank=True, choices=[('en_stock', 'En stock'), ('faible_stock', 'Faible stock'), ('rupture', 'Rupture de stock'), ('precommande', 'Précommande')], default='en_stock', max_length=20),
        ),
        migrations.AddField(
            model_name='produit',
            name='etat',
            field=models.CharField(blank=True, choices=[('neuf', 'Neuf'), ('occasion', 'Occasion'), ('reconditionne', 'Reconditionné')], default='neuf', max_length=20),
        ),
        migrations.AddField(
            model_name='produit',
            name='garantie_mois',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Sans garantie'), (3, '3 mois'), (6, '6 mois'), (12, '12 mois'), (24, '24 mois')], default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='hauteur',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hauteur en cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='image_principale_index',
            field=models.PositiveIntegerField(default=1, help_text="Index de l'image principale (1 à 4)"),
        ),
        migrations.AddField(
            model_name='produit',
            name='largeur',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Largeur en cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='longueur',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Longueur en cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='modeles_compatibles',
            field=models.JSONField(blank=True, default=list, help_text='Liste des modèles compatibles'),
        ),
        migrations.AddField(
            model_name='produit',
            name='mots_cles',
            field=models.JSONField(blank=True, default=list, help_text='Mots-clés pour la recherche'),
        ),
        migrations.AddField(
            model_name='produit',
            name='pays_origine',
            field=models.CharField(blank=True, choices=[('japon', 'Japon'), ('allemagne', 'Allemagne'), ('france', 'France'), ('coree_sud', 'Corée du Sud'), ('chine', 'Chine'), ('usa', 'États-Unis'), ('italie', 'Italie'), ('espagne', 'Espagne'), ('turquie', 'Turquie'), ('inde', 'Inde')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='produit',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Poids en kg', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='reference_oem',
            field=models.CharField(blank=True, default='', help_text='Référence OEM / constructeur', max_length=100),
        ),
    ]
