# Generated by Django 6.0.5 on 2026-07-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_produit_annee_debut_produit_annee_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
