# Generated by Django 6.0.5 on 2026-07-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_produit_date_ajout'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='compatibilites',
            field=models.JSONField(blank=True, default=list, help_text='Liste détaillée des compatibilités (marque, modèle, version, motorisation, années)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='conditions_garantie',
            field=models.TextField(blank=True, default='', help_text='Conditions de la garantie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='couleur',
            field=models.CharField(blank=True, default='', help_text='Couleur', max_length=100),
        ),
        migrations.AddField(
            model_name='produit',
            name='delai_preparation',
            field=models.CharField(blank=True, choices=[('24h', '24 heures'), ('48h', '48 heures'), ('72h', '72 heures'), ('4_5j', '4 à 5 jours'), ('6_7j', '6 à 7 jours'), ('7j_plus', 'Plus de 7 jours')], default='24h', help_text='Délai de préparation avant expédition', max_length=20),
        ),
        migrations.AddField(
            model_name='produit',
            name='description_courte',
            field=models.TextField(blank=True, default='', help_text='Description courte (accroche)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='description_detaillee',
            field=models.TextField(blank=True, default='', help_text='Description détaillée complète'),
        ),
        migrations.AddField(
            model_name='produit',
            name='fabricant',
            field=models.CharField(blank=True, default='', help_text='Fabricant', max_length=100),
        ),
        migrations.AddField(
            model_name='produit',
            name='garantie_disponible',
            field=models.BooleanField(default=False, help_text='Produit sous garantie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='livraison_disponible',
            field=models.BooleanField(default=False, help_text='Livraison disponible pour ce produit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='matiere',
            field=models.CharField(blank=True, default='', help_text='Matière / matériau', max_length=100),
        ),
        migrations.AddField(
            model_name='produit',
            name='precautions',
            field=models.TextField(blank=True, default='', help_text="Précautions d'usage"),
        ),
        migrations.AddField(
            model_name='produit',
            name='quantite_min',
            field=models.PositiveIntegerField(blank=True, help_text='Quantité minimale de commande', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='retrait_magasin',
            field=models.BooleanField(default=False, help_text='Retrait en magasin disponible'),
        ),
        migrations.AddField(
            model_name='produit',
            name='seuil_alerte',
            field=models.PositiveIntegerField(blank=True, help_text="Seuil d'alerte stock faible", null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(help_text='Description détaillée du produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='marque',
            field=models.CharField(blank=True, help_text='Marque de la pièce', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='reference',
            field=models.CharField(blank=True, help_text='Référence interne vendeur (SKU)', max_length=50, null=True),
        ),
    ]
