# Generated by Django 6.0.5 on 2026-07-24 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_produit_compatibilites_produit_conditions_garantie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mouvementstock',
            options={'ordering': ['-date_mouvement']},
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='motif',
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='observation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produit',
            name='date_derniere_maj_stock',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='catalog.produit'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('retour', 'Retour'), ('correction', 'Correction')], max_length=20),
        ),
    ]
