# Generated by Django 6.0.5 on 2026-07-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_alter_mouvementstock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='nb_utilisations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='nom',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='promotion',
            name='nombre_max_utilisations',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre maximal d'utilisations de la promotion", null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='quantite_min',
            field=models.PositiveIntegerField(blank=True, help_text='Quantité minimale pour bénéficier de la promotion', null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='type_promotion',
            field=models.CharField(choices=[('pourcentage', 'Réduction en pourcentage'), ('montant_fixe', 'Réduction en montant fixe'), ('vente_flash', 'Vente Flash'), ('offre_speciale', 'Offre spéciale'), ('produit_vedette', 'Produit en vedette'), ('nouveau_produit', 'Nouveau produit'), ('dernieres_pieces', 'Dernières pièces disponibles')], default='pourcentage', max_length=20),
        ),
        migrations.AddField(
            model_name='promotion',
            name='valeur_reduction',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant fixe de réduction (pour montant_fixe) ou valeur selon le type', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='pourcentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('a_venir', 'À venir'), ('terminee', 'Terminée'), ('suspendue', 'Suspendue')], default='a_venir', max_length=20),
        ),
    ]
