# Generated by Django 6.0.5 on 2026-07-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_promotion_description_promotion_heure_debut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marques/')),
                ('description', models.TextField(blank=True, null=True)),
                ('est_visible', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('datecreation', models.DateTimeField(auto_now_add=True)),
                ('datemodification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['ordre', 'nom']},
        ),
        migrations.AddField(
            model_name='categorie',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
