# Generated by Django 6.0.5 on 2026-08-06 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_fournisseur_statut'),
        ('catalog', '0033_marque_alter_categorie_options_categorie_ordre'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_recherchee', models.CharField(help_text='Nom ou description de la pièce recherchée', max_length=200)),
                ('marque_vehicule', models.CharField(blank=True, default='', max_length=100)),
                ('modele_vehicule', models.CharField(blank=True, default='', max_length=100)),
                ('annee_vehicule', models.CharField(blank=True, default='', max_length=20)),
                ('reference', models.CharField(blank=True, default='', help_text='Référence éventuelle', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Description complémentaire')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='demandes-pieces/')),
                ('nom_client', models.CharField(blank=True, default='', max_length=100)),
                ('email_client', models.EmailField(blank=True, default='', max_length=254)),
                ('telephone_client', models.CharField(blank=True, default='', max_length=20)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours de traitement'), ('traitee', 'Traitée'), ('cloturee', 'Clôturée')], default='nouvelle', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.client')),
            ],
            options={
                'db_table': 'catalog_demande_piece',
                'ordering': ['-date_creation'],
            },
        ),
    ]
