# Generated by Django 6.0.5 on 2026-08-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_demande_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseurproduit',
            name='prix_vente',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente spécifique à ce fournisseur/magasin. Si vide, le prix du produit est utilisé.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fournisseurproduit',
            name='stock_disponible',
            field=models.PositiveIntegerField(blank=True, help_text='Stock spécifique à ce fournisseur/magasin. Si vide, le stock du produit est utilisé.', null=True),
        ),
    ]
