# Generated by Django 6.0.5 on 2026-08-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_fournisseurproduit_prix_vente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='nombre_avis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='note_moyenne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
