# Generated by Django 6.0.5 on 2026-09-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_produit_nombre_avis_produit_note_moyenne'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fournisseurproduit',
            unique_together={('produit', 'fournisseur')},
        ),
    ]
