# Generated by Django 6.0.5 on 2026-09-13 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_unique_fournisseurproduit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default='', help_text='Nom commun du groupe (auto-généré)', max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='produit_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='catalog.produitgroup'),
        ),
    ]
