# Generated by Django 6.0.1 on 2026-02-25 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_utilisateur_options_utilisateur_date_joined_and_more'),
        ('delivery', '0002_initial'),
        ('orders', '0002_commande_reference_alter_commande_administrateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='adresse_livraison',
        ),
        migrations.AddField(
            model_name='livraison',
            name='adresse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.adresse'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='account.client'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='commande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='orders.commande'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.livreur'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='remarque',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('PREPAREE', 'Préparée'), ('EN_COURS', 'En cours'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='PREPAREE', max_length=30),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.vehicule'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.livreur'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='plaque',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type',
            field=models.CharField(choices=[('MOTO', 'Moto'), ('VOITURE', 'Voiture'), ('CAMION', 'Camion')], max_length=20),
        ),
    ]
