# Generated by Django 6.0.5 on 2026-08-09 00:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_fournisseur_statut'),
        ('delivery', '0005_alter_adresse_id_alter_livraison_id_and_more'),
        ('fournisseur', '0005_magasin_delai_livraison_estime_and_more'),
        ('orders', '0010_commande_adresse_livraison_commande_telephone_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartenaireLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('identifiant', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_nom', models.CharField(blank=True, default='', max_length=100)),
                ('zone_couverte', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'delivery_partenaire',
            },
        ),
        migrations.AlterModelOptions(
            name='adresse',
            options={'ordering': ['-est_principale', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='livraison',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RemoveField(
            model_name='adresse',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='adresse',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='adresse',
            name='rue',
        ),
        migrations.AddField(
            model_name='adresse',
            name='adresse',
            field=models.TextField(blank=True, default='', verbose_name='Adresse complète'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='adresse',
            name='est_principale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adresse',
            name='instructions',
            field=models.TextField(blank=True, default='', verbose_name='Instructions supplémentaires'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='adresse',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='adresse',
            name='nom_destinataire',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nom du destinataire'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='point_de_repere',
            field=models.TextField(blank=True, default='', verbose_name='Point de repère'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='quartier',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='adresse',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='date_attribution',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='delai_estime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Délai estimé'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='account.fournisseur'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='livraison',
            name='magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='fournisseur.magasin'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='mode_tarif',
            field=models.CharField(blank=True, choices=[('non_defini', 'Non défini'), ('fixe', 'Tarif fixe'), ('zone', 'Tarif par zone'), ('distance', 'Tarif par distance'), ('magasin', 'Tarif défini par le magasin'), ('partenaire', 'Tarif défini par le partenaire')], default='non_defini', max_length=30),
        ),
        migrations.AddField(
            model_name='livraison',
            name='responsable_type',
            field=models.CharField(choices=[('non_attribue', 'Non attribué'), ('magasin', 'Magasin'), ('partenaire', 'Partenaire externe'), ('livreur', 'Livreur interne')], default='non_attribue', max_length=30),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='ville',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='delivery.adresse'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='orders.commande'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='account.livreur'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='remarque',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='statut',
            field=models.CharField(choices=[('en_attente_attribution', "En attente d'attribution"), ('livraison_attribuee', 'Livraison attribuée'), ('en_preparation', 'En préparation'), ('prise_en_charge', 'Prise en charge'), ('en_cours_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('echec_livraison', 'Échec de livraison'), ('annulee', 'Annulée')], default='en_attente_attribution', max_length=30),
        ),
        migrations.AlterModelTable(
            name='adresse',
            table='delivery_adresse',
        ),
        migrations.AlterModelTable(
            name='livraison',
            table='delivery_livraison',
        ),
        migrations.AlterModelTable(
            name='vehicule',
            table='delivery_vehicule',
        ),
        migrations.AddField(
            model_name='livraison',
            name='partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='delivery.partenairelivraison'),
        ),
    ]
