# Generated by Django 6.0.5 on 2026-07-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='lien',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='fournisseur_notification',
        ),
    ]
