# Generated by Django 6.0.5 on 2026-07-22 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_fournisseur_raison_refus_fournisseur_validated_by_and_more'),
        ('fournisseur', '0002_alter_notification_options_notification_lien_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_magasin', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='magasins/logos/')),
                ('photo_couverture', models.ImageField(blank=True, null=True, upload_to='magasins/covers/')),
                ('description', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse_complete', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('horaires_ouverture', models.JSONField(blank=True, default=dict)),
                ('jours_ouverture', models.CharField(blank=True, max_length=255)),
                ('livraison_disponible', models.BooleanField(default=False)),
                ('retrait_magasin', models.BooleanField(default=False)),
                ('rayon_livraison_km', models.PositiveIntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='magasin', to='account.fournisseur')),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
                'db_table': 'fournisseur_magasin',
            },
        ),
    ]
