# Generated by Django 6.0.5 on 2026-08-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0003_magasin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='destinataire_type',
            field=models.CharField(choices=[('fournisseur', 'Fournisseur'), ('admin', 'Admin'), ('client', 'Client')], max_length=20),
        ),
    ]
