# Generated by Django 6.0.5 on 2026-08-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0004_alter_notification_destinataire_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='magasin',
            name='delai_livraison_estime',
            field=models.CharField(blank=True, help_text='Ex: Sous 24h, 48h...', max_length=100),
        ),
        migrations.AddField(
            model_name='magasin',
            name='frais_livraison',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='magasin',
            name='mode_tarif_livraison',
            field=models.CharField(blank=True, choices=[('non_defini', 'Non défini'), ('fixe', 'Tarif fixe'), ('zone', 'Tarif par zone'), ('distance', 'Tarif par distance')], default='non_defini', max_length=30),
        ),
        migrations.AddField(
            model_name='magasin',
            name='tarif_gratuit_desous',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Frais de livraison offerts à partir de ce montant', max_digits=10),
        ),
    ]
