# Generated by Django 6.0.5 on 2026-08-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0006_magasin_nombre_avis_magasin_note_moyenne'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='importance',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('danger', 'Critique')], default='info', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='objet_id',
            field=models.PositiveIntegerField(blank=True, help_text="ID de l'objet lié", null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='objet_type',
            field=models.CharField(blank=True, help_text="Type de l'objet lié", max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='destinataire_type',
            field=models.CharField(choices=[('client', 'Client'), ('fournisseur', 'Fournisseur'), ('admin', 'Administrateur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ORDER_CREATED', 'Commande créée'), ('PAYMENT_SUCCESS', 'Paiement confirmé'), ('PAYMENT_FAILED', 'Paiement échoué'), ('ORDER_ACCEPTED', 'Commande acceptée'), ('ORDER_REFUSED', 'Commande refusée'), ('ORDER_PREPARING', 'Commande en préparation'), ('ORDER_READY', 'Commande prête'), ('ORDER_DELIVERING', 'Commande en livraison'), ('ORDER_DELIVERED', 'Commande livrée'), ('ORDER_CANCELLED', 'Commande annulée'), ('PART_REQUEST_OFFER', 'Nouvelle offre sur demande'), ('OFFER_ACCEPTED', 'Offre acceptée'), ('REVIEW_CREATED', 'Avis publié'), ('REVIEW_REPLIED', 'Réponse à un avis'), ('NEW_SUPPLIER', 'Nouveau fournisseur à valider'), ('ADMIN_ALERT', 'Alerte admin'), ('commande', 'Nouvelle commande'), ('stock', 'Alerte stock'), ('promotion', 'Promotion'), ('avis', 'Nouvel avis'), ('systeme', 'Système'), ('demande', 'Demande de pièce'), ('offre', 'Offre')], max_length=40),
        ),
    ]
