# Generated by Django 6.0.5 on 2026-08-09 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_fournisseur_statut'),
        ('orders', '0011_alter_commande_mode_paiement_alter_commande_statut_and_more'),
        ('payments', '0004_alter_paiement_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RenameField(
            model_name='paiement',
            old_name='date_paiement',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='type',
        ),
        migrations.AddField(
            model_name='paiement',
            name='cle_idempotence',
            field=models.CharField(blank=True, db_index=True, help_text="Clé unique de l'initiation, utilisée pour éviter les doubles paiements côté serveur.", max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Métadonnées techniques du prestataire. Ne jamais y stocker de secret.'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='motif_erreur',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='moyen',
            field=models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement'), ('a_la_livraison', 'Paiement à la livraison'), ('a_la_retrait', 'Paiement au retrait')], default='a_la_livraison', max_length=30),
        ),
        migrations.AddField(
            model_name='paiement',
            name='provider_reference',
            field=models.CharField(blank=True, help_text='Référence technique retournée par le prestataire de paiement futur.', max_length=255),
        ),
        migrations.AddField(
            model_name='paiement',
            name='remboursement_montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='remboursement_motif',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='account.client'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='orders.commande'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('annule', 'Annulé'), ('remboursement_demande', 'Remboursement demandé'), ('remboursement_en_cours', 'Remboursement en cours'), ('rembourse', 'Remboursé'), ('remboursement_refuse', 'Remboursement refusé')], default='en_attente', max_length=40),
        ),
    ]
