# Generated by Django 6.0.1 on 2026-02-16 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_embauche', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('point_fidelite', models.IntegerField(blank=True, null=True)),
                ('mode_paiement_favoris', models.CharField(blank=True, max_length=50, null=True)),
                ('note_livreur', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('livreur_id', models.IntegerField(blank=True, null=True)),
                ('administrateur_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('intention_inscription', models.BooleanField(blank=True, null=True)),
                ('conversion_tentative', models.BooleanField(blank=True, null=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('temps_moyen_visite', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('zone_livraison', models.CharField(max_length=100)),
                ('statut', models.CharField(max_length=20)),
                ('nombre_livraison', models.IntegerField(blank=True, null=True)),
                ('note_client_moyenne', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
        ),
    ]
