# Generated by Django 5.2.6 on 2026-05-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_utilisateur_options_utilisateur_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Administrateur')], default='client', max_length=30),
        ),
    ]
