# Generated by Django 6.0.1 on 2026-02-25 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_utilisateur_options_utilisateur_date_joined_and_more'),
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSupportClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_ouverts', models.IntegerField(blank=True, null=True)),
                ('tickets_fermes', models.IntegerField(blank=True, null=True)),
                ('note_satisfaction', models.FloatField(blank=True, null=True)),
                ('langues_parlees', models.CharField(max_length=100)),
                ('temps_reponse_moyen', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateField()),
                ('type_alerte', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=50)),
                ('gestionnaire_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.gestionnairestock')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.produit')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('commentaire', models.TextField()),
                ('date', models.DateField()),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.categorie')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.client')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.livreur')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField()),
                ('type_action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree_traitement', models.TimeField(blank=True, null=True)),
                ('agent_support_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.agentsupportclient')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('administrateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.administrateur')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('lu', models.BooleanField(blank=True, null=True)),
                ('gestionnaire_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.gestionnairestock')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('statut', models.CharField(max_length=30)),
                ('date_soumission', models.DateField()),
                ('agent_support_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.agentsupportclient')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.client')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_ouverture', models.DateTimeField()),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(max_length=20)),
                ('priorite', models.CharField(max_length=20)),
                ('agent_support_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.agentsupportclient')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.client')),
            ],
        ),
        migrations.CreateModel(
            name='MessageSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=100)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField()),
                ('statut', models.CharField(max_length=20)),
                ('agent_support_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.agentsupportclient')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.client')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.ticket')),
            ],
        ),
    ]
