# Generated by Django 6.0.5 on 2026-09-14 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_commande_id_alter_lignecommande_id_and_more'),
        ('support', '0006_demande_partenariat'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='achat_verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avis',
            name='approuve',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='avis',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis_commande', to='orders.commande'),
        ),
        migrations.AddField(
            model_name='avis',
            name='date_reponse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avis',
            name='note_communication',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avis',
            name='note_delai',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avis',
            name='note_livraison',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avis',
            name='note_qualite_produit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avis',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='avis',
            name='reponse_fournisseur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avis',
            name='reponse_fournisseur_nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
