"""

Django settings for automecastore project.



Generated by 'django-admin startproject' using Django 6.0.1.



For more information on this file, see

https://docs.djangoproject.com/en/6.0/topics/settings/



For the full list of settings and their values, see

https://docs.djangoproject.com/en/6.0/ref/settings/

"""



import os
from pathlib import Path

from datetime import timedelta

# Charger automatiquement le fichier .env s'il existe à la racine du projet.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except Exception:
    pass



# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent





# Quick-start development settings - unsuitable for production

# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!

# DEBUG from environment — defaults to True if no .env file (dev mode), False otherwise
_env_file = BASE_DIR / '.env'
if os.environ.get('DEBUG') is not None:
    DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'
elif _env_file.exists():
    DEBUG = False
else:
    DEBUG = True  # No .env file → assume development

# SECRET_KEY from environment — fail explicitly in production if missing
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-key-do-not-use-in-production'
    else:
        raise ValueError('SECRET_KEY must be set in environment for production')

# ALLOWED_HOSTS from environment (comma-separated)
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost,0.0.0.0').split(',')





# Application definition



INSTALLED_APPS = [

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'rest_framework',

    'rest_framework_simplejwt',

    'corsheaders',



    # APPS CREER

    'account',

    'catalog',

    'delivery',

    'orders',

    'payments',

    'support',

    'fournisseur',
    'admin_api',
    'demandes',
]



REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework_simplejwt.authentication.JWTAuthentication',

        'rest_framework.authentication.SessionAuthentication',

    ),

    'DEFAULT_PERMISSION_CLASSES': (

        'rest_framework.permissions.IsAuthenticated',

    ),

    'DEFAULT_THROTTLE_CLASSES': (

        'rest_framework.throttling.AnonRateThrottle',

        'rest_framework.throttling.UserRateThrottle',

        'rest_framework.throttling.ScopedRateThrottle',

    ),

    'DEFAULT_THROTTLE_RATES': {

        'anon': os.environ.get('THROTTLE_ANON', '60/min'),

        'user': os.environ.get('THROTTLE_USER', '120/min'),

        'login': os.environ.get('THROTTLE_LOGIN', '5/min'),

        'register': os.environ.get('THROTTLE_REGISTER', '3/min'),

        'payment': os.environ.get('THROTTLE_PAYMENT', '10/min'),

        'order': os.environ.get('THROTTLE_ORDER', '10/min'),

    },

}



MIDDLEWARE = [

    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]



ROOT_URLCONF = 'automecastore.urls'



TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]



WSGI_APPLICATION = 'automecastore.wsgi.application'





# Database

# https://docs.djangoproject.com/en/6.0/ref/settings/#databases



DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.postgresql',

        'NAME': 'automecastore_dev',

        'USER': 'postgres',

        'PASSWORD': '2004',

        'HOST': 'localhost',

        'PORT': '5432',

    }

}



AUTH_USER_MODEL = 'account.Utilisateur'



# Password validation

# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators



AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]





# Internationalization

# https://docs.djangoproject.com/en/6.0/topics/i18n/



LANGUAGE_CODE = 'en-us'



TIME_ZONE = 'UTC'



USE_I18N = True



USE_TZ = True





# Static files (CSS, JavaScript, Images)

# https://docs.djangoproject.com/en/6.0/howto/static-files/



STATIC_URL = 'static/'



# Media files (User uploaded content)

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'



SIMPLE_JWT = {

    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),

    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),

}



# Configuration CORS pour permettre les requêtes du frontend

# CORS — configurable via environment (comma-separated)
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:4200,http://127.0.0.1:4200'
    ).split(',') if origin.strip()
]

CORS_ALLOW_CREDENTIALS = True

# Never allow all origins in production
CORS_ALLOW_ALL_ORIGINS = False


# Configuration email
# - En développement (par défaut) : les emails s'affichent dans la console.
# - En production : définissez EMAIL_BACKEND=smtp dans le fichier .env
#   ainsi que EMAIL_HOST_USER / EMAIL_HOST_PASSWORD pour envoyer réellement.
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend'
    if os.environ.get('EMAIL_HOST_USER')
    else 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'AutoMecaStore <noreply@automecastore.sn>')
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000')

# -----------------------------
# Production security settings
# -----------------------------
if not DEBUG:
    # HTTPS / SSL
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True'
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

    # Proxy
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'