# Generated by Django 6.0.5 on 2026-08-09 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0014_alter_fournisseur_statut'),
        ('catalog', '0036_produit_nombre_avis_produit_note_moyenne'),
        ('delivery', '0006_partenairelivraison_alter_adresse_options_and_more'),
        ('orders', '0011_alter_commande_mode_paiement_alter_commande_statut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, help_text='Référence unique REQ-AAAAMMJJ-XXXXXX', max_length=20, null=True, unique=True)),
                ('nom_contact', models.CharField(blank=True, default='', max_length=100)),
                ('email_contact', models.EmailField(blank=True, default='', max_length=254)),
                ('telephone_contact', models.CharField(blank=True, default='', max_length=30)),
                ('piece_recherchee', models.CharField(max_length=200)),
                ('reference_oem', models.CharField(blank=True, default='', max_length=100)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('marque_vehicule', models.CharField(blank=True, default='', max_length=50)),
                ('modele_vehicule', models.CharField(blank=True, default='', max_length=50)),
                ('annee_vehicule', models.IntegerField(blank=True, null=True)),
                ('motorisation', models.CharField(blank=True, default='', max_length=100)),
                ('version', models.CharField(blank=True, default='', max_length=100)),
                ('ville', models.CharField(blank=True, default='', max_length=100)),
                ('quartier', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('photo_piece', models.ImageField(blank=True, null=True, upload_to='demandes/pieces/')),
                ('photo_vehicule', models.ImageField(blank=True, null=True, upload_to='demandes/vehicules/')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_recherche', 'En recherche'), ('offres_recues', 'Offres reçues'), ('acceptee', 'Acceptée'), ('commande_creee', 'Commande créée'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='nouvelle', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='account.client')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_source', to='orders.commande')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='catalog.produit')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='delivery.vehicule')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='OffreFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('occasion', 'Occasion'), ('reconditionne', 'Reconditionné')], default='neuf', max_length=20)),
                ('garantie', models.CharField(blank=True, default='', max_length=100)),
                ('disponibilite', models.CharField(choices=[('immediate', 'Disponible immédiatement'), ('sous_2_jours', 'Sous 2 jours'), ('sous_1_semaine', 'Sous 1 semaine'), ('sur_commande', 'Sur commande')], default='immediate', max_length=20)),
                ('delai', models.CharField(blank=True, default='', max_length=100)),
                ('mode_reception', models.CharField(choices=[('retrait', 'Retrait en magasin'), ('livraison', 'Livraison'), ('retrait_ou_livraison', 'Retrait ou livraison')], default='retrait_ou_livraison', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée'), ('convertie', 'Convertie en commande')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offre_source', to='orders.commande')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='demandes.demandepiece')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='account.fournisseur')),
            ],
            options={
                'ordering': ['prix', '-date_creation'],
            },
        ),
    ]
