# Generated by Django 6.0.1 on 2026-02-25 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_utilisateur_options_utilisateur_date_joined_and_more'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField()),
                ('statut', models.CharField(max_length=30)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('administrateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.administrateur')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.client')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.livreur')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('sous_total', models.FloatField()),
                ('prix_unitaire', models.IntegerField(default=0)),
                ('commande', models.ForeignKey(blank=True, db_column='commande_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.commande')),
                ('produit', models.ForeignKey(blank=True, db_column='produit_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_panier', models.CharField(max_length=100)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.client')),
                ('invite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.invite')),
            ],
        ),
    ]
