# Generated by Django 6.0.5 on 2026-07-20 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_utilisateur_email_alerts_enabled_and_more'),
        ('orders', '0006_alter_commande_id_alter_lignecommande_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='account.client'),
        ),
    ]
