# Generated by Django 6.0.5 on 2026-07-24 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def map_and_seed_commandes(apps, schema_editor):
    Commande = apps.get_model('orders', 'Commande')
    HistoriqueCommande = apps.get_model('orders', 'HistoriqueCommande')
    mapping = {
        'en_attente': 'en_attente_confirmation',
        'validee': 'acceptee',
        'expediee': 'en_cours_livraison',
        'livree': 'livree',
        'annulee': 'annulee',
    }
    for cmd in Commande.objects.all():
        if cmd.statut in mapping:
            cmd.statut = mapping[cmd.statut]
            cmd.save(update_fields=['statut'])
        HistoriqueCommande.objects.get_or_create(
            commande=cmd,
            statut=cmd.statut,
            commentaire='Commande créée',
            defaults={'motif': '', 'utilisateur_nom': 'Système'}
        )


def reverse_map_commandes(apps, schema_editor):
    Commande = apps.get_model('orders', 'Commande')
    HistoriqueCommande = apps.get_model('orders', 'HistoriqueCommande')
    reverse_mapping = {
        'en_attente_confirmation': 'en_attente',
        'acceptee': 'validee',
        'en_preparation': 'en_attente',
        'prete_a_retirer': 'validee',
        'en_cours_livraison': 'expediee',
        'livree': 'livree',
        'terminee': 'livree',
        'refusee': 'annulee',
        'annulee': 'annulee',
        'nouvelle_commande': 'en_attente',
    }
    for cmd in Commande.objects.all():
        cmd.statut = reverse_mapping.get(cmd.statut, 'en_attente')
        cmd.save(update_fields=['statut'])
    HistoriqueCommande.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_commande_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='commentaire_fournisseur',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement'), ('a_la_livraison', 'Paiement à la livraison')], default='a_la_livraison', max_length=30),
        ),
        migrations.AddField(
            model_name='commande',
            name='mode_reception',
            field=models.CharField(blank=True, choices=[('livraison', 'Livraison à domicile'), ('retrait_magasin', 'Retrait en magasin')], default='livraison', max_length=30),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('nouvelle_commande', 'Nouvelle commande'), ('en_attente_confirmation', 'En attente de confirmation'), ('acceptee', 'Acceptée'), ('en_preparation', 'En préparation'), ('prete_a_retirer', 'Prête à être retirée'), ('en_cours_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('terminee', 'Terminée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='nouvelle_commande', max_length=30),
        ),
        migrations.CreateModel(
            name='HistoriqueCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(blank=True, choices=[('nouvelle_commande', 'Nouvelle commande'), ('en_attente_confirmation', 'En attente de confirmation'), ('acceptee', 'Acceptée'), ('en_preparation', 'En préparation'), ('prete_a_retirer', 'Prête à être retirée'), ('en_cours_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('terminee', 'Terminée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], max_length=30)),
                ('commentaire', models.TextField(blank=True)),
                ('motif', models.TextField(blank=True)),
                ('utilisateur_nom', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='orders.commande')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.RunPython(map_and_seed_commandes, reverse_map_commandes),
    ]
