# Generated by Django 6.0.5 on 2026-08-06 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_fournisseur_statut'),
        ('fournisseur', '0003_magasin'),
        ('orders', '0008_commande_commentaire_fournisseur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='account.fournisseur'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='fournisseur.magasin'),
        ),
        migrations.AddField(
            model_name='panieritem',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panier_items', to='account.fournisseur'),
        ),
        migrations.AddField(
            model_name='panieritem',
            name='magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panier_items', to='fournisseur.magasin'),
        ),
    ]
