# Generated by Django 6.0.5 on 2026-08-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_lignecommande_fournisseur_lignecommande_magasin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.TextField(blank=True, help_text='Adresse de livraison si mode livraison'),
        ),
        migrations.AddField(
            model_name='commande',
            name='telephone_client',
            field=models.CharField(blank=True, help_text='Téléphone de contact pour cette commande', max_length=20),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='mode_reception',
            field=models.CharField(blank=True, choices=[('livraison', 'Livraison à domicile'), ('retrait_magasin', 'Retrait en magasin')], default='livraison', max_length=30),
        ),
        migrations.AddField(
            model_name='panieritem',
            name='mode_reception',
            field=models.CharField(blank=True, choices=[('livraison', 'Livraison à domicile'), ('retrait_magasin', 'Retrait en magasin')], default='livraison', max_length=30),
        ),
    ]
