# Generated by Django 6.0.5 on 2026-08-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_commande_adresse_livraison_commande_telephone_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement'), ('a_la_livraison', 'Paiement à la livraison'), ('a_la_retrait', 'Paiement au retrait')], default='a_la_livraison', max_length=30),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('nouvelle_commande', 'Nouvelle commande'), ('en_attente_paiement', 'En attente de paiement'), ('en_attente_confirmation', 'En attente de confirmation'), ('acceptee', 'Acceptée'), ('en_preparation', 'En préparation'), ('prete_a_retirer', 'Prête à être retirée'), ('en_cours_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('terminee', 'Terminée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='nouvelle_commande', max_length=30),
        ),
        migrations.AlterField(
            model_name='historiquecommande',
            name='statut',
            field=models.CharField(blank=True, choices=[('nouvelle_commande', 'Nouvelle commande'), ('en_attente_paiement', 'En attente de paiement'), ('en_attente_confirmation', 'En attente de confirmation'), ('acceptee', 'Acceptée'), ('en_preparation', 'En préparation'), ('prete_a_retirer', 'Prête à être retirée'), ('en_cours_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('terminee', 'Terminée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], max_length=30),
        ),
    ]
