# Generated by Django 6.0.5 on 2026-08-11 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_commande_mode_paiement_alter_commande_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquecommande',
            name='ligne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='orders.lignecommande'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='statut',
            field=models.CharField(blank=True, choices=[('nouvelle_commande', 'Nouvelle commande'), ('en_attente_paiement', 'En attente de paiement'), ('en_attente_confirmation', 'En attente de confirmation'), ('acceptee', 'Acceptée'), ('en_preparation', 'En préparation'), ('prete_a_retirer', 'Prête à être retirée'), ('en_cours_livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('terminee', 'Terminée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='nouvelle_commande', max_length=30),
        ),
    ]
