# Generated by Django 6.0.5 on 2026-08-11 01:07

from django.db import migrations


def init_statut_ligne(apps, schema_editor):
    LigneCommande = apps.get_model('orders', 'LigneCommande')
    lignes = list(LigneCommande.objects.select_related('commande'))
    for ligne in lignes:
        if ligne.commande:
            ligne.statut = ligne.commande.statut
    if lignes:
        LigneCommande.objects.bulk_update(lignes, ['statut'], batch_size=500)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_historiquecommande_ligne_lignecommande_statut'),
    ]

    operations = [
        migrations.RunPython(init_statut_ligne, reverse),
    ]
