# Generated by Django 6.0.5 on 2026-09-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20260811_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='invite_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='commande',
            name='invite_nom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='commande',
            name='invite_prenom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
